### ISSUE TITLE
ES6 notation

### ISSUE THREAD

**Issue by kai-adsk** [deeprjs/deepr#1]
Hi. I just had a look at Deepr for the first time. It looks very interesting :-)

While reading the documentation I was wondering if we could make use of ES6 notation to make this even more similar to GraphQL

Instead of this

```
{
  "movie": {
    "title": true,
    "year": true
  }
}
```

we could write

```
{
  "movie": {
    "title",
    "year"
  }
}
```

where "title" would evaluate to "title": "title" in ES6 and it would therefore be "true" as well - so maybe this already works without code changes.

Just a thought... :-)

**Comment by mvila** [comment]
Hi @kai-adsk,

`{"movie": {"title", "year"}}` is not valid, even in ES6.

We could write `{"movie": {title, year}}`, but then `title` and `year` have to be defined upfront.

Also, keep in mind that Deepr doesn't specify any serialization language. I used JSON as an example, but anything could be used, such as YAML, XML, or even your own created language.
