### ISSUE TITLE
Server - Client architecture

### ISSUE THREAD

**Issue by antonkatz** [deeprjs/deepr#2]
Is there a client-side implementation for sending queries to the server side?

Great job by the way!

**Comment by mvila** [comment]
Deepr specifies how to serialize queries, but the client/server communication is up to you. For example, to send a query to a server, any HTTP client ([Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), [Axios](https://github.com/axios/axios), [Got](https://github.com/sindresorhus/got), etc.) would works.
