### ISSUE TITLE
Parallel requests in REST

### ISSUE THREAD

**Issue by sammyhenningsson** [deeprjs/deepr#4]
Hi,

Interesting project! You mention parallel requests a bit and that it's not supported with REST, I think this is incorrect. HTTP2 has been out for half a decade now (and HTTP3 is around the corner). HTTP2 supports parallel requests thus  REST does do.

Cheers,
Sammy

**Comment by mvila** [comment]
Thanks @sammyhenningsson, I didn't think about HTTP/2.

I edited the [README](https://github.com/deeprjs/deepr#feature-comparison).
